name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Ejecutar solo pruebas de e2e
      run: npx playwright test tests/e2e/
      continue-on-error: true

    - name: Verificar estado de pruebas
      if: failure()
      run: echo "❌ Algunas pruebas fallaron. Revisa los detalles arriba."

    - name: Final exitoso
      if: success()
      run: echo "✅ Todas las pruebas pasaron correctamente."

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Subir URL como artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages-url
        path: gh-pages-url.txt

    - name: Subir reporte a GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
    
    - name: Mostrar URL de GitHub Pages
      run: |
          echo "Reporte disponible en: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
